### ISSUE TITLE
Wrong License

### ISSUE THREAD

**Issue by kameko** [emgucv/emgutf#1]
For anyone reading this, you don't have to put up with the cancerous GPL or pay hundreds of dollars for an API _wrapper_, just use https://github.com/shimat/opencvsharp, it's BSD-3, just like the real OpenCV.

**Comment by emgucv** [comment]
I could start to argue if the issues should be titled "Wrong License".

Emgu CV use dual license model as described here: http://www.emgu.com/wiki/index.php/Licensing: 

Many open source projects (such as MySql and MogoDB) use dual licensing: https://en.wikipedia.org/wiki/Business_models_for_open-source_software#Dual-licensing

GPL license allows the Academic community to use the software for free. On the other hand, the commercial license allows business to purchase commercial license for a small fee and use it in their commercial product. The cost is small compares with the time (and money) they save on hiring a consultant. The license fee, in term, contributes to the continue development of the software and cover the cost of running the project. 

You are feel to choose the software library you use. In this case, opencvsharp is an option. 

Dual licensed projects tend to be successful in the long term because the developers are financially supported and are motivated to develop, maintain and improve the software. Open source projects without a financial of academic backing (e.g. developer need to focus on their work, or graduated from university, or leaves his/her research institution) will be less likely to keep maintaining the opensource project. (I can't remember where I read the paper, It was about 10 years ago when this project starts) 

Open CV development are backed by big corporation and research community (Itseez, Intel, Willow Garage etc). Our development are purely based on License fee and consulting. 

Hope that explains the reason behind the choice of the dual license model.

**Comment by kameko** [comment]
No not really that's actually a pretty gay reason

**Comment by emgucv** [comment]
Seems that we cannot have a constructive discussion. There will be no more comments from us on this issue.

**Comment by developer-power-ro** [comment]
Seems like a reasonable explanation to me.
