### ISSUE TITLE
Can CUDA version fall back to CPU when no GPU is installed?

### ISSUE THREAD

**Issue by JohnTenney** [emgucv/emgutf#11]
We have built our app with CUDA EMGU TF support, and it works great--but only on machines with an NVidia GPU installed. If there is no NVidia GPU, it gives an error reporting "nvcuda.dll" cannot be found. Is there anything you can do to ensure that the app will run even on systems that have no GPU at all?

**Comment by emgucv** [comment]
Sorry about that, John.  You have asked me if the CUDA build can fall back on CPU and I have tested on a workstation without a CUDA card and it works. I just double check on that workstation, and notice that the workstation has a nvidia driver installed on it even thought it doesn't have a NVidia Graphic card. We used to have an NVidia Graphic card on that work station and that is why.

So the key here is to have an NVidia Graphic card driver. It will fall back to run on CPU as long as the NVidia Graphic card driver presents, when there is no graphic card. 

On machines with no CUDA graphic card and no Nvidia driver, you will need to download "nvcuda.dll" and paste it into the load path. I have tried with copying to the "c:\Windows\System32\" folder, but it should also work by putting the file in the "x64" folder or the folder where the executable is.

Getting the driver is relative straight forward if you have a workstation with an NVidia Card. Just grab it from the "C:\Windows\System32\" folder. If you don't, then it is a bit tricky. You can download the Nvidia driver from Nvidia's website. Attempts to install it, it will ask you to extract it to a folder, e.g.

 C:\NVIDIA\DisplayDriver\388.31\Win8_Win7_64\International\Display.Driver

Extract it, you can attempt to install the driver but it will fail because it couldn't detect the graphic card. But there should be a file called: 

C:\NVIDIA\DisplayDriver\388.31\Win8_Win7_64\International\Display.Driver\nvcuda64.dl_

**Comment by JohnTenney** [comment]
Here's a hack that I used that seems to work on either GPU or non-GPU systems. In a static constructor for 'MyEmguTFAlgorithms' class, I added the following code. I'm ok using this going forward, but it would be nicer if you were able to take care of it more cleverly! I have to include both DLL's in my distribution.

```
static MyEmguTFAlgorithms()
{
    var targetPath = Path.Combine(x64Path, "tfextern.dll");
    if (!LoadLibrary(Path.Combine(x64Path, "tfextern_gpu.dll"), targetPath))
        LoadLibrary(Path.Combine(x64Path, "tfextern_cpu.dll"), targetPath);
}

private static bool LoadLibrary(string libPath, string targetPath)
{
    var ptr = Toolbox.LoadLibrary(libPath);
    var isLoaded = ptr != IntPtr.Zero;
    if (isLoaded) {
        Toolbox.FreeLibrary(ptr);
        if (!File.Exists(targetPath) || new FileInfo(targetPath).Length != new FileInfo(libPath).Length)
            File.Copy(libPath, targetPath, true);
    }
    return isLoaded;
}
```
