### ISSUE TITLE
Attempting to JIT compile method '(wrapper native-to-managed) int Emgu.TF.Lite.TfLiteInvoke:TfliteErrorHandler (int,intptr)' while running in aot-only mode.

### ISSUE THREAD

**Issue by Ralpharoo** [emgucv/emgutf#46]
We've purchased the commercial version of Emgu.TF but are receiving errors whilst running the unmodified Lite iOS example solution on real iOS devices. This works in the simulator, but not on real iOS devices.

**Library**: _libemgutflite-pro-2.4.0.1059_

**Solution:** _Emgu.TF.Lite.Example.iOS.sln_ (unmodified, Xamarin Forms)

**IDE:** _Visual Studio for Mac 8.8.3 (build 16) with Mono 6.12.0.107_

**Configuration:** _Debug | iPhone_ (iPhone 11 Max on iOS 14.3)

**Error:** _Attempting to JIT compile method '(wrapper native-to-managed) int Emgu.TF.Lite.TfLiteInvoke:TfliteErrorHandler (int,intptr)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information._

**StackTrace:**   _at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_delegate_to_ftnptr(object)
  at (wrapper managed-to-native) Emgu.TF.Lite.TfLiteInvoke.RedirectError(Emgu.TF.Lite.TfLiteInvoke/TfliteErrorCallback)
  at Emgu.TF.Lite.TfLiteInvoke..cctor () [0x00088] in /libemgutflite-pro/Emgu.TF.Lite/TFLiteInvoke.cs:294_ 

![Screen Shot 2020-12-09 at 3 31 52 pm](https://user-images.githubusercontent.com/24926020/101589212-b9360380-3a33-11eb-93da-ad7fdf2aaf9e.png)

Are you aware of this issue? Or have any suggestions to resolve? Further to this, **Release | iPhone** build breaks throwing ~50 other errors.

**Comment by emgucv** [comment]
Hi Ralpharoo,

The issue has been fixed in the following 3 commits:
https://github.com/emgucv/emgutf/commit/a38695ec25e503629b14eb595cc13d71b51aeae3 
https://github.com/emgucv/emgutf/commit/eee233db46ed0e850c1e4fa5a9fd23704143083e 
https://github.com/emgucv/emgutf/commit/dfcc4b72497b29cc54022322a0e04227951d6269 

Please send an email to support@emgu.com and we can upload a development build for you.

Or, as a quick fix, you can also comment out the specific line that is causing the issue. Our proper fixed listed above will call the RedirectError method in TfLiteInvokeIOS constructor instead.

We will have another 2.4 release once the final tensorflow 2.4 stable release is out.

**Comment by Ralpharoo** [comment]
@emgucv Awesome, thank you. Those commits have resolved it locally for the time being.

I've emailed but happy to wait for the new stable 2.4 release before upgrading.

Thanks again for the prompt resolution.
