### ISSUE TITLE
How to convert from Mat to Tensor and vice versa

### ISSUE THREAD

**Issue by cipheran93-2** [emgucv/emgutf#49]
So i want to make a prediction with my tflite model. For input i use NativeImageIO.ReadImageFileToTensor<byte> but when i tried to convert it back to Mat but the image is broken

![](https://cdn.discordapp.com/attachments/636905024731217931/788260754465226782/unknown.png)
What is shown
![](https://cdn.discordapp.com/attachments/636905024731217931/788260834966896670/thu1.png)
Original image
![](https://cdn.discordapp.com/attachments/636905024731217931/788260736484376596/unknown.png)
 Any ideas ?

**Comment by cipheran93-2** [comment]
Any ideas?

**Comment by emgucv** [comment]
It depends on the type of your output tensor. Is it trained to output a single channel (gray scale) floating point data of the same dimension of the input tensor?

In your code, you are constructing a Mat of single color channel (gray scale), floating point data using this constructor:
http://www.emgu.com/wiki/files/4.4.0/document/html/c8424736-2d44-c5d6-212f-31dedfe6fb95.htm

If it is an color image, please try using this constructor to create a  3 channel image type Mat instead:
http://www.emgu.com/wiki/files/4.4.0/document/html/1401abd7-7f10-9c71-58cf-02d042adacec.htm

If the output depth is float, is the range between 0.0-1.0? If so, you need to scale it backup to [0, 255) byte data type for it to display correctly. Otherwise, any value between [0.0,1.0) will get convert to pixel value of 0 (black).
